[project]
name = "hw1-llm-prompt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.2.0",
    "dotenv>=0.9.9",
    "openai>=2.2.0",
]
